import { callLLM } from "./llmClient.js";
import { CODEGEN_SYSTEM_PROMPT } from "./prompts/codegenSystemPrompt.js";
import { CodeFileMapSchema, type Brief, type AssetRef, type CodeFileMap } from "./schemas.js";

const MAX_CODEGEN_RETRIES = 3;

export function ensureRootFile(files: CodeFileMap, brief: Brief): CodeFileMap {
  if (files["Root.tsx"]) {
    return {
      ...files,
      "Root.tsx": enforceMainCompositionId(files["Root.tsx"]),
    };
  }

  console.log("[Codegen Middleware] Root.tsx was not generated by LLM. Generating fallback Root.tsx...");

  // Parse files for exported components
  const imports: string[] = [];
  const sequences: string[] = [];
  let currentFrame = 0;
  const fps = 30;

  // Track if we have an ambient background component
  let backgroundComponent: string | null = null;

  for (const [filename, content] of Object.entries(files) as Array<[string, string]>) {
    if (!filename.endsWith(".tsx")) continue;
    const moduleName = filename.replace(/\.tsx$/, "");

    // Regex to find named exports: export const MyComponent = ... or export function MyComponent() ...
    const exportRegex = /export\s+(?:const|function)\s+([A-Z]\w*)/g;
    let match: RegExpExecArray | null;
    const exportsInFile: string[] = [];

    while ((match = exportRegex.exec(content)) !== null) {
      exportsInFile.push(match[1]);
    }

    if (exportsInFile.length > 0) {
      const primaryComponent = exportsInFile[0];
      imports.push(`import { ${primaryComponent} } from "./${moduleName}";`);

      // Detect background files
      if (primaryComponent.toLowerCase().includes("background") || primaryComponent.toLowerCase().includes("ambient")) {
        backgroundComponent = primaryComponent;
      } else {
        // Assume default scene duration of 90 frames (3 seconds) if not mapped to a brief scene
        const durationInFrames = 90;
        sequences.push(`      <Sequence from={${currentFrame}} durationInFrames={${durationInFrames}}>
        <${primaryComponent} font="Inter" startFrame={0} />
      </Sequence>`);
        currentFrame += durationInFrames;
      }
    }
  }

  // Calculate total duration
  const totalDurationFrames = Math.max(90, currentFrame);

  const rootContent = `import React from "react";
import { Composition, AbsoluteFill, Sequence } from "remotion";
${imports.join("\n")}

const MainSequence: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "#000000" }}>
      {/* Background layer */}
      ${backgroundComponent ? `<${backgroundComponent} />` : "<!-- No ambient background detected -->"}
      
      {/* Sequential scenes */}
${sequences.join("\n")}
    </AbsoluteFill>
  );
};

export const Root: React.FC = () => {
  return (
    <Composition
      id="Main"
      component={MainSequence}
      durationInFrames={${totalDurationFrames}}
      fps={${fps}}
      width={1920}
      height={1080}
    />
  );
};
`;

  return {
    ...files,
    "Root.tsx": rootContent,
  };
}

function enforceMainCompositionId(rootContent: string): string {
  return rootContent.replace(/id\s*=\s*"([^"]+)"/, 'id="Main"');
}

function sanitizeSceneFiles(files: CodeFileMap): CodeFileMap {
  const result: CodeFileMap = {};
  for (const [filename, content] of Object.entries(files)) {
    if (filename === "Root.tsx") {
      result[filename] = content;
      continue;
    }
    let cleaned = content;

    // Remove Composition import token from remotion import lines
    cleaned = cleaned.replace(
      /import\s*\{([^}]*)\}\s*from\s*["']remotion["']\s*;?\n?/g,
      (match, group: string) => {
        const tokens = group.split(",").map((t: string) => t.trim()).filter(Boolean);
        const filtered = tokens.filter((t: string) => t !== "Composition");
        if (filtered.length === 0) return "";
        return `import { ${filtered.join(", ")} } from "remotion";\n`;
      },
    );

    // Remove self-closing <Composition /> tags
    cleaned = cleaned.replace(/<Composition\b[^>]*\/>/g, "");
    // Remove <Composition>...</Composition> blocks (multiline)
    cleaned = cleaned.replace(/<Composition\b[^>]*>[\s\S]*?<\/Composition>/g, "");
    // Remove any remaining standalone Composition references (React.createElement etc.)
    cleaned = cleaned.replace(/,\s*Composition(?=\s*[},])/g, "");
    cleaned = cleaned.replace(/\bComposition\s*,/g, "");

    result[filename] = cleaned;
  }
  return result;
}

export async function generateCode(
  brief: Brief,
  assets: AssetRef[] = [],
  modelName?: string
): Promise<CodeFileMap> {
  const userContent = JSON.stringify({ brief, assets }, null, 2);

  for (let attempt = 0; attempt <= MAX_CODEGEN_RETRIES; attempt++) {
    const messages = [
      { role: "system" as const, content: CODEGEN_SYSTEM_PROMPT },
      { role: "user" as const, content: `Generate Remotion React code for this Creative Brief:\n${userContent}` },
    ];

    const responseText = await callLLM(messages, true, modelName);
    let json: any;

    try {
      json = JSON.parse(responseText);
    } catch {
      if (attempt < MAX_CODEGEN_RETRIES) {
        console.warn(`[Codegen] JSON parse failed on attempt ${attempt + 1}, retrying...`);
        continue;
      }
      throw new Error(`Failed to parse LLM response as JSON after ${MAX_CODEGEN_RETRIES + 1} attempts.`);
    }

    try {
      const files = CodeFileMapSchema.parse(json);

      const cleanedFiles: CodeFileMap = {};
      for (const [key, val] of Object.entries(files)) {
        const cleanKey = key.replace(/^src\//, "");
        cleanedFiles[cleanKey] = val;
      }

      return sanitizeSceneFiles(ensureRootFile(cleanedFiles, brief));
    } catch (parseErr: any) {
      if (attempt < MAX_CODEGEN_RETRIES) {
        console.warn(`[Codegen] Schema validation failed on attempt ${attempt + 1}: ${parseErr.message}`);
        continue;
      }
      throw new Error(`Generated code failed validation after ${MAX_CODEGEN_RETRIES + 1} attempts: ${parseErr.message}`);
    }
  }

  throw new Error("Codegen failed unexpectedly.");
}
